version: '3.8'
services:
  js-client:
    build:
      context: ./js-client
    volumes:
      - ./js-client:/app
      - exclude:/app/node_modules/
    ports:
      - "3000:3000"
volumes:
  exclude:
