# Use this file a template to generate `credentials.yml.enc`
# 1. specifying an editor:
#     `export EDITOR="nano"`
# 2. using the rails credential cli
#     `bin/rails credentials:edit`
# Refer to: https://guides.rubyonrails.org/security.html#custom-credentials

auth0:
  # hash goes here
  secret_key_base:
  # configured or generated auth0 domain
  domain:
  # your configured api audience.
  # QUESTION: how would this look for accessing multiple apis??
  audience:
